[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["crates/schematic", "crates/test-app"]

[workspace.dependencies]
chrono = "0.4.38"
indexmap = "2.2.6"
miette = "7.2.0"
regex = "1.10.4"
relative-path = "1.9.3"
reqwest = { version = "0.12.4", default-features = false }
rust_decimal = "1.35.0"
semver = "1.0.22"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.34"
toml = "0.8.12"
url = "2.5.0"
