[package]
name = "schematic_macros"
version = "0.1.6"
edition = "2021"
license = "MIT"
description = "Macros for the schematic crate."
repository = "https://github.com/moonrepo/schematic"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.1"
proc-macro2 = "1.0.57"
quote = "1.0.26"
syn = { version = "2.0.16", features = ["full"] }
