[package]
name = "schematic_macros"
version = "0.11.3"
edition = "2021"
license = "MIT"
description = "Macros for the schematic crate."
repository = "https://github.com/moonrepo/schematic"

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
darling = "0.20.3"
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full"] }

[features]
default = []
schema = []
