[book]
authors = ["Miles Johnson"]
language = "en"
multilingual = false
src = "src"
title = "Schematic"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/milesj/schematic"
git-repository-icon = "fa-github"
